# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: task.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntask.proto\x12\x04todo\x1a\x1egoogle/protobuf/wrappers.proto\"G\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x1e\n\x05state\x18\x03 \x01(\x0e\x32\x0f.todo.TaskState\"$\n\x05Tasks\x12\x1b\n\x07pending\x18\x01 \x03(\x0b\x32\n.todo.Task\".\n\tTaskQuery\x12!\n\x08selected\x18\x01 \x03(\x0e\x32\x0f.todo.TaskState*M\n\tTaskState\x12\x08\n\x04OPEN\x10\x00\x12\x0c\n\x08\x41SSIGNED\x10\x01\x12\x0f\n\x0bPROGRESSING\x10\x02\x12\x08\n\x04\x44ONE\x10\x03\x12\r\n\tCANCELLED\x10\x04\x32\xc2\x01\n\x07Taskapi\x12\x33\n\x07\x61\x64\x64Task\x12\x1c.google.protobuf.StringValue\x1a\n.todo.Task\x12\x33\n\x07\x64\x65lTask\x12\x1c.google.protobuf.UInt64Value\x1a\n.todo.Task\x12\"\n\x08\x65\x64itTask\x12\n.todo.Task\x1a\n.todo.Task\x12)\n\tlistTasks\x12\x0f.todo.TaskQuery\x1a\x0b.todo.Tasksb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKSTATE']._serialized_start=211
  _globals['_TASKSTATE']._serialized_end=288
  _globals['_TASK']._serialized_start=52
  _globals['_TASK']._serialized_end=123
  _globals['_TASKS']._serialized_start=125
  _globals['_TASKS']._serialized_end=161
  _globals['_TASKQUERY']._serialized_start=163
  _globals['_TASKQUERY']._serialized_end=209
  _globals['_TASKAPI']._serialized_start=291
  _globals['_TASKAPI']._serialized_end=485
# @@protoc_insertion_point(module_scope)
