# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: task.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntask.proto\"\x1f\n\x08TaskDesc\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\"\'\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"\x10\n\x02Id\x12\n\n\x02id\x18\x01 \x01(\x03\"\x1d\n\x05Tasks\x12\x14\n\x05tasks\x18\x01 \x03(\x0b\x32\x05.Task\"\x07\n\x05\x45mpty2X\n\x07Taskapi\x12\x19\n\x07\x61\x64\x64Task\x12\t.TaskDesc\x1a\x03.Id\x12\x15\n\x07\x64\x65lTask\x12\x03.Id\x1a\x05.Task\x12\x1b\n\tlistTasks\x12\x06.Empty\x1a\x06.Tasksb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKDESC']._serialized_start=14
  _globals['_TASKDESC']._serialized_end=45
  _globals['_TASK']._serialized_start=47
  _globals['_TASK']._serialized_end=86
  _globals['_ID']._serialized_start=88
  _globals['_ID']._serialized_end=104
  _globals['_TASKS']._serialized_start=106
  _globals['_TASKS']._serialized_end=135
  _globals['_EMPTY']._serialized_start=137
  _globals['_EMPTY']._serialized_end=144
  _globals['_TASKAPI']._serialized_start=146
  _globals['_TASKAPI']._serialized_end=234
# @@protoc_insertion_point(module_scope)
